### ISSUE TITLE
Related projects

### ISSUE THREAD

**Issue by Guria** [cuzzo/react-bem#2]
Would be great to have section in readme with links on projects with another approaches to bringing bem naming in react:
- [react-bem-helper](https://github.com/marcohamersma/react-bem-helper)
- [bem-classnames](https://github.com/pocotan001/bem-classnames)
- [bem-cn](https://github.com/albburtsev/bem-cn)
- [b_](https://github.com/azproduction/b_)

**Comment by cuzzo** [comment]
Done. Thanks for the suggestion.
